### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by vrad-exe** [suchipi/half-life-vox-console#15]
There's no license on this repository, which means [using it is technically illegal](https://choosealicense.com/no-permission/). Given the fact that you released the code on a public repository in the first place, I'm assuming this wasn't your intent.

If your concern is over the inclusion of Half-Life game files in the repository, it should be possible to add a note stating that the files under `public/vox/` are copyright Valve and not covered by the license.

**Comment by suchipi** [comment]
Thanks! As you suspected, I didn't license it because I didn't know how to best handle the inclusion of Valve's assets. But I wrote up a license that I think is probably good enough. Certainly good enough to let people use the website parts (which I licensed under the MIT license).

Love your name and avatar btw ;3

Fixed in https://github.com/suchipi/half-life-vox-console/commit/1331565bdc47339fce27cecb30c189d79c2ca338
